development: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: dba
  password: admin
  database: reservy_development
  allow_concurrency: true
  pool: 5
  min_messages: warning

test:
  <<: *default
  database: reservy_test
  min_messages: error

production:
  adapter: postgresql
  encoding: unicode
  database: reservy_production
  allow_concurrency: true
  pool: 5
